export { default as LandingPage } from "./LandingPage"
export { default as AboutPage } from "./About"
export { default as LoginPage } from "./Login"
export { default as SignupPage } from "./Signup"
export { default as MultiShop } from "./MultiShop"
export { default as SingleShop } from "./SingleShop"
